---
- name: INSTALL | vim
  tags:
    - install
  block:
    - name: INSTALL | Ensure vim is installed
      become: True
      ansible.builtin.apt:
        name: vim
        state: present

- name: CONFIGURE | vim
  tags:
  - configure
  block:
    - name: CONFIGURE | Find vim config file
      ansible.builtin.find:
        paths: "{{ ansible_user_dir }}"
        recurse: True
        hidden: True
        patterns:
          - '.vimrc'
          - 'vimrc'
        file_type: file
      register: vimrc_files

    - name: Show found vimrc files
      debug:
        var: vimrc_files.files
