---
- name: INSTALL | vim
  tags:
    - install
  block:
    - name: INSTALL | Ensure vim is installed
      become: True
      ansible.builtin.apt:
        name: vim
        state: present

- name: CONFIGURE | vim
  tags:
  - configure
  block:
    - name: CONFIGURE | Find existing vim config files
      ansible.builtin.find:
        paths: "{{ ansible_user_dir }}"
        recurse: True
        hidden: True
        patterns:
          - '.vimrc'
          - 'vimrc'
        file_type: file
      register: vimrc_files

    - name: CONFIGURE | Ensure VIMRC path exists when set
      ansible.builtin.file:
        path: "{{ MYVIMRC | dirname }}"
        state: directory
      when: MYVIMRC is defined

    - name: CONFIGURE | Move found vimrc files to MYVIMRC dirname
      ansible.builtin.command:
        cmd: mv "{{ item.path }}" "{{ MYVIMRC | dirname }}/"
      with_items: "{{ vimrc_files.files }}"
      when: MYVIMRC is defined
      loop_control:
        label: "{{ item.path }}"
